### ISSUE TITLE
How to add custom router?

### ISSUE THREAD

**Issue by imagine10255** [TheRobBrennan/demo-nextjs-v5#27]
Hi, I use typescript in nextjs 5
but use custom router show typescript error is:
```
Error:(9, 22) TS2306:File '/Users/apple/Documents/project/with-typescript-app/src/routes.ts' is not a module.
```
can you help me ? thx o_o

**Comment by TheRobBrennan** [comment]
The routing used in this project doesn't do anything too fancy. Just simple routes based on top level pages and parameters that are passed in to those components. That lets you have paths like `/people/developers/rob`, `/people/developers`, or `/people` appear in the browser, but internally are handled through pages within the NextJS app.
