### ISSUE TITLE
Prod SourceMapping?

### ISSUE THREAD

**Issue by BrianJFeldman** [TheRobBrennan/demo-nextjs-v5#31]
Hey @TheRobBrennan,

I'm struggling to get the tooling right for a 'staging' environment. Do you have an example on how to setup the next.config for a built version of the app that shows correct, unminified source maps?

**Comment by TheRobBrennan** [comment]
Hmmmm...Good question, @BrianJFeldman - I haven't looked into the source mapping part, but that is something I can take a peek at. Lemme mull it over some. 

In the meantime, if you find a way to resolve it, feel free to create a pull request 😀

**Comment by TheRobBrennan** [comment]
@BrianJFeldman Great news!! I was talking with one of the core NextJS developers and discovered they had an easy solution to the problem. There is a Zeit plug-in that can handle source mapping.

For details, please grab the latest `master` from this repo - or check out my merged pull request at https://github.com/TheRobBrennan/demo-nextjs-v5/pull/32

Enjoy!!! Lemme know how it works out for ya.
